#Templatedont change
          - name: RCLONE_CONFIG_S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: RCLONE_CONFIG_S3_ENDPOINT
                name: ${SECRET}
          - name: RCLONE_CONFIG_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: RCLONE_CONFIG_S3_ACCESS_KEY_ID
                name: ${SECRET}
          - name: RCLONE_CONFIG_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: RCLONE_CONFIG_S3_SECRET_ACCESS_KEY
                name: ${SECRET}
          - name: RCLONE_CONFIG_S3_ENV_AUTH
            valueFrom:
              secretKeyRef:
                key: RCLONE_CONFIG_S3_ENV_AUTH
                name: ${SECRET}
          - name: RCLONE_CONFIG_S3_PROVIDER
            valueFrom:
              secretKeyRef:
                key: RCLONE_CONFIG_S3_PROVIDER
                name: ${SECRET}
          - name: RCLONE_CONFIG_S3_TYPE
            valueFrom:
              secretKeyRef:
                key: RCLONE_CONFIG_S3_TYPE
                name: ${SECRET}
          - name: SSL_CERT_FILE
            value: /tmp/ca/host-tls.crt

        