#!/bin/bash

if [ "$ENVLOCATION" = "master" ]; then

RG=${1:-$RESOURCE_GROUP}

#--sku {Premium_AzureFrontDoor, Standard_AzureFrontDoor}

C="az afd profile create -g ${RG} --profile-name ${FRONT_DOOR_PROFILE} --sku ${SKU_FRONT_DOOR}"

./run-cmd "${C}"


C="az afd endpoint create -g ${RG} --endpoint-name ${FRONT_DOOR_ENDPOINT} --profile-name ${FRONT_DOOR_PROFILE} --enabled-state Enabled"

./run-cmd "${C}"

fi